version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "100k"
    max-file: "3"
services:

  # app-basic:
  #   build: ./
  #   logging: *default-logging
  #   volumes:
  #   - ./app/:/app/
  #   command: sh
  #   tty: true
  #   ports: 
  #     - "8001:8001"

  # app-router:
  #   build: ./
  #   logging: *default-logging
  #   volumes:
  #     - ./app-router/:/app/
  #   command: sh
  #   tty: true
  #   ports: 
  #     - "8001:8001"

  # app-flux:
  #   build: ./
  #   logging: *default-logging
  #   volumes:
  #     - ./app-flux/:/app/
  #   command: sh
  #   tty: true
  #   ports: 
  #     - "8001:8001"

  # app-redux:
  #   build: ./
  #   logging: *default-logging
  #   volumes:
  #     - ./app-redux/:/app/
  #   command: sh
  #   tty: true
  #   ports: 
  #     - "8001:8001"
  #     - "18080:18080"

  # app-redux2:
  #   build: ./
  #   logging: *default-logging
  #   volumes:
  #     - ./app-redux2/:/app/
  #   command: sh
  #   tty: true
  #   ports: 
  #     - "8001:8001"
  #     - "18080:18080"
        
  app-react-typescript:
    build: ./
    logging: *default-logging
    volumes:
      - ./app-react-typescript/:/app/
    command: sh
    tty: true
    ports: 
      - "8001:8001"
