version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "100k"
    max-file: "3"
services:

  # app-basic:
  #   build: ./
  #   logging: *default-logging
  #   volumes:
  #   - ./app/:/app/
  #   command: sh
  #   tty: true
  #   ports: 
  #     - "8001:8001"

  # app-router:
  #   build: ./
  #   logging: *default-logging
  #   volumes:
  #     - ./app-router/:/app/
  #   command: sh
  #   tty: true
  #   ports: 
  #     - "8001:8001"

  app-flux:
    build: ./
    logging: *default-logging
    volumes:
      - ./app-router/:/app/
    command: sh
    tty: true
    ports: 
      - "8001:8001"