FROM php:7.3-apache

RUN apt update && apt-get install -y git libzip-dev
RUN docker-php-ext-install pdo_mysql zip

RUN a2enmod rewrite

WORKDIR /var/www

RUN docker-php-ext-install opcache
RUN pecl install apcu
RUN docker-php-ext-enable apcu